version: "3.9"

services:
  postgresql:
    image: 'bitnami/mysql:8.0.31'
    ports:
      - '3302:3302'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_USER=admin
      - MYSQL_ROOT_PASSWORD=admin!123
      - MYSQL_DATABASE=marketplace
    networks:
      - mysql

volumes:
  mysql_data:

networks:
  mysql: