version: "3.9"

services:
  postgresql:
    image: 'bitnami/postgresql:15.1.0'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin@123.
      - POSTGRESQL_DATABASE=marketplace
    networks:
      - postgresql

volumes:
  postgresql_data:

networks:
  postgresql: