spring:
  datasource:
    url: jdbc:h2:mem:marketplace;NON_KEYWORDS=USER
    username: admin
    password: admin!123
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
      generate_statistics: true
      dialect: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default

logging:
  level:
    org:
      hibernate:
        type: trace
        sql: debug
        orm:
          jdbc:
            bind: trace
        stat: debug
        SQL_SLOW: info
        cache: debug
