spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marketplace
    username: admin
    password: admin!123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop # TODO configure database creation script and change this to validate(?)
      format_sql: true